### ISSUE TITLE
module not working 

### ISSUE THREAD

**Issue by iliasmeg** [slametps/MMM-RandomQuranAyah#1]
hi the module is not working can you please check it .

**Comment by slametps** [comment]
Have you check the forum?
https://forum.magicmirror.builders/topic/1795/mmm-randomquranayah/33?page=4

**Comment by bibi05** [comment]
Hi, would it possible to add a css file in your repo? or maybe you can explain me how to use custom css with MMM-rrandomquranayah please?

**Comment by slametps** [comment]
you can check other module to add a css. You can fork this repo, modify the files, and do a PR (Pull-Request).

**Comment by bibi05** [comment]
Thx for your feedback. I will check how other modules use css but not sure I’m skilled to do this currently.

**Comment by bibi05** [comment]
Hi slametps,
After checking other module, i come up with the following css proposal. Could you please valide it? afterward i will check how to fork, modify the file and pull as all of this is new to me but i am keen to learn :)

.MMM-RandomQuranAyah .txtArabic {
	width: 280px;
	color: red 
}
.MMM-RandomQuranAyah .txtTranslation {
	width: 280px;
	color: blue 
}

**Comment by slametps** [comment]
That is not gonna work. I'll try to modify the code supporting css. I'll let you know, if ready.

**Comment by bibi05** [comment]
Thx for your help. will be very nice to see how you did it. a way for me to learn :) ws

**Comment by slametps** [comment]
> Hi slametps,
> After checking other module, i come up with the following css proposal. Could you please valide it? afterward i will check how to fork, modify the file and pull as all of this is new to me but i am keen to learn :)
> 
> .MMM-RandomQuranAyah .txtArabic {
> width: 280px;
> color: red
> }
> .MMM-RandomQuranAyah .txtTranslation {
> width: 280px;
> color: blue
> }

Please update your repo with the latest code.

**Comment by bibi05** [comment]
> > Hi slametps,
> > After checking other module, i come up with the following css proposal. Could you please valide it? afterward i will check how to fork, modify the file and pull as all of this is new to me but i am keen to learn :)
> > .MMM-RandomQuranAyah .txtArabic {
> > width: 280px;
> > color: red
> > }
> > .MMM-RandomQuranAyah .txtTranslation {
> > width: 280px;
> > color: blue
> > }
> 
> Please update your repo with the latest code.

wow so cool you did it! thx you so much. I don't have access right now to my MM but will update my repo this weekend. thx again!

**Comment by bibi05** [comment]
sorry for the late reply. it works! thank you very much for the update!

**Comment by slametps** [comment]
Ok. glad to hear that.
