### ISSUE TITLE
no Quran verse displayed.

### ISSUE THREAD

**Issue by Jamy2020** [slametps/MMM-RandomQuranAyah#4]
Hello, I have did everything as described, but there is simply no Quran verse displayed. What can that be? can you plewase help me? Below is my config.

[config.txt](https://github.com/slametps/MMM-RandomQuranAyah/files/4477946/config.txt)

**Comment by slametps** [comment]
Your config seems OK. Can you check or post your MM or PM2 log here?

**Comment by Jamy2020** [comment]
here ist the pm2 log and the configcheck.
the other modules run without any problem.

> pi@raspberrypi:~ $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2020-04-16T20:00:29: PM2 log: App [mm:0] exited with code [127] via signal [SIGINT]
PM2        | 2020-04-16T20:00:29: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2020-04-16T20:00:29: PM2 log: App [mm:0] online
PM2        | 2020-04-16T20:00:29: PM2 log: App [mm:0] exited with code [127] via signal [SIGINT]
PM2        | 2020-04-16T20:00:29: PM2 log: Script /home/pi/mm.sh had too many unstable restarts (16). Stopped. "errored"
PM2        | 2020-04-16T21:04:08: PM2 log: Change detected on path config/config.js for app MagicMirror - restarting
PM2        | 2020-04-16T21:04:08: PM2 log: Stopping app:MagicMirror id:1
PM2        | 2020-04-16T21:04:09: PM2 log: pid=630 msg=failed to kill - retrying in 100ms
PM2        | 2020-04-16T21:04:09: PM2 log: pid=630 msg=failed to kill - retrying in 100ms
PM2        | 2020-04-16T21:04:09: PM2 log: pid=630 msg=failed to kill - retrying in 100ms
PM2        | 2020-04-16T21:04:09: PM2 log: pid=630 msg=failed to kill - retrying in 100ms
PM2        | 2020-04-16T21:04:09: PM2 log: App [MagicMirror:1] exited with code [0] via signal [SIGINT]
PM2        | 2020-04-16T21:04:09: PM2 log: pid=630 msg=process killed
PM2        | 2020-04-16T21:04:09: PM2 log: App [MagicMirror:1] starting in -fork mode-
PM2        | 2020-04-16T21:04:09: PM2 log: App [MagicMirror:1] online

/home/pi/.pm2/logs/mm-out.log last 15 lines:
/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found
0|mm       | /home/pi/mm.sh: line 1: cd: too many arguments
0|mm       | /home/pi/mm.sh: line 2: DISPLAY: command not found

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
1|MagicMir | npm ERR! errno 1
1|MagicMir | npm ERR! magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
1|MagicMir | npm ERR! Exit status 1
1|MagicMir | npm ERR! 
1|MagicMir | npm ERR! Failed at the magicmirror@2.11.0 start script.
1|MagicMir | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1|MagicMir | 
1|MagicMir | npm ERR! A complete log of this run can be found in:
1|MagicMir | npm ERR!     /home/pi/.npm/_logs/2020-04-16T18_00_16_572Z-debug.log
1|MagicMir | 
1|MagicMir | (process:921): Gtk-WARNING **: 20:00:33.491: Locale not supported by C library.
1|MagicMir | 	Using the fallback 'C' locale.
1|MagicMir | 
1|MagicMir | (process:2188): Gtk-WARNING **: 21:04:11.299: Locale not supported by C library.
1|MagicMir | 	Using the fallback 'C' locale.

/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
1|MagicMir | [2020-04-16 21:04:12.677] [LOG]    All module helpers loaded.
1|MagicMir | [2020-04-16 21:04:12.804] [LOG]    Starting server on port 8080 ... 
1|MagicMir | [2020-04-16 21:04:12.832] [LOG]    Server started ...
1|MagicMir | [2020-04-16 21:04:12.834] [LOG]    Connecting socket for: updatenotification
1|MagicMir | [2020-04-16 21:04:12.836] [LOG]    Connecting socket for: calendar
1|MagicMir | [2020-04-16 21:04:12.838] [LOG]    Starting node helper for: calendar
1|MagicMir | [2020-04-16 21:04:12.840] [LOG]    Connecting socket for: newsfeed
1|MagicMir | [2020-04-16 21:04:12.843] [LOG]    Starting module: newsfeed
1|MagicMir | [2020-04-16 21:04:12.844] [LOG]    Sockets connected & modules started ...
1|MagicMir | [2020-04-16 21:04:12.980] [LOG]    Launching application.
1|MagicMir | [2020-04-16 21:04:15.201] [LOG]    Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/46/GER_Holidays.ics - Interval: 300000
1|MagicMir | [2020-04-16 21:04:15.251] [LOG]    Create new news fetcher for url: http://rss.focus.de/fol/XML/rss_folnews_eilmeldungen.xml - Interval: 300000
1|MagicMir | [2020-04-16 21:27:15.846] [LOG]    Use existing news fetcher for url: http://rss.focus.de/fol/XML/rss_folnews_eilmeldungen.xml
1|MagicMir | [2020-04-16 22:11:39.163] [LOG]    Use existing news fetcher for url: http://rss.focus.de/fol/XML/rss_folnews_eilmeldungen.xml
1|MagicMir | [2020-04-16 22:12:59.833] [LOG]    Use existing news fetcher for url: http://rss.focus.de/fol/XML/rss_folnews_eilmeldungen.xml



pi@raspberrypi:~/MagicMirror $ npm run config:check

> magicmirror@2.11.0 config:check /home/pi/MagicMirror
> node tests/configs/check_config.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/tests/configs/check_config.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.11.0 config:check: `node tests/configs/check_config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magicmirror@2.11.0 config:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-16T20_17_49_402Z-debug.log
pi@raspberrypi:~/MagicMirror $

**Comment by slametps** [comment]
From your PM2 logs, module MMM-RandomQuranAyah is not loaded. 
Pls try to move the MMM-RandomQuranAyah  config as the first module to be loaded. I thinks other errors logged in PM2-logs prevent the module to be loaded correctly.

If the module loaded succesfully, it will display some log entries as following:
```
...
Initializing new module helper ...
Module helper loaded: MMM-RandomQuranAyah
...
Connecting socket for: MMM-RandomQuranAyah
Starting node_helper.js for MMM-RandomQuranAyah.
...
MMM-RandomQuranAyah node helper received a socket notification: START_QURAN - Payload: [object Object]
/nodehelper/get arabic with statuscode-200
/nodehelper/get translation with statuscode-200
/nodehelper/result-Al-Mulk:9
...
```
