### ISSUE TITLE
App Blanks entire Magic Mirror

### ISSUE THREAD

**Issue by ishratd** [slametps/MMM-RandomQuranAyah#5]
I am trying to use your above app via Magic Mirror, though each time I set it up in a different location it blanks my whole screen.

**Comment by slametps** [comment]
pls post your config here.

**Comment by slametps** [comment]
have you check your MM/PM2 error log?

**Comment by ishratd** [comment]
Hi

Please see below
[config.txt](https://github.com/slametps/MMM-RandomQuranAyah/files/5162204/config.txt)

**Comment by slametps** [comment]
You should test one-by-one the module you used to check which module config causing the error. I check the MMM-RandomQuranAyah config is OK.

**Comment by ishratd** [comment]
Ok thanks, Looking at the log, I get a "No helper found for module: MMM-RandomQuranAyah.

**Comment by ishratd** [comment]
All sorted! I had to install the async module helper.

Thank you.

**Comment by slametps** [comment]
Alhamdulillah. glad to hear that.
