### ISSUE TITLE
API is broken, updating code for new API

### ISSUE THREAD

**Issue by Sheikh-A** [slametps/MMM-RandomQuranAyah#6]
Looks like https://alquran.cloud/api changed their API endpoints, here is the new endpoint formats: 

node_helper.js
```
var quranArabicURL = "https://api.alquran.cloud/v1/ayah/" + randomAyah + "/editions/ar";
var quranTranslationURL = "https://api.alquran.cloud/v1/ayah/" + randomAyah + "/editions/" + payload.translationLang;

```

**Comment by slametps** [comment]
Ok, I'll fix it ASAP.
Thx for notify me.

**Comment by slametps** [comment]
> Looks like https://alquran.cloud/api changed their API endpoints, here is the new endpoint formats:
> 
> node_helper.js
> 
> ```
> var quranArabicURL = "https://api.alquran.cloud/v1/ayah/" + randomAyah + "/editions/ar";
> var quranTranslationURL = "https://api.alquran.cloud/v1/ayah/" + randomAyah + "/editions/" + payload.translationLang;
> ```

@Sheikh-A : I checked the old API is still available and return the result as expected. If you got the broken or unexpected result, pls post your config for this module.

**Comment by Sheikh-A** [comment]
Looks like the API endpoint is working now, a few days ago I tried importing the module and nothing was showing up, so I updated my endpoint in the node_helper.js file as above but looks like it is working now! Closing out for now, thanks for building this 💯 !!!
