### ISSUE TITLE
Change Arabic Text

### ISSUE THREAD

**Issue by shak4031** [slametps/MMM-RandomQuranAyah#7]
I would like to use a different Arabic text, is that possible.  The Arabic is difficult for me to read, are there other options for Arabic text.  I am not referring to the translation in "English" in my case, I am referring to they style of Arabic.

**Comment by slametps** [comment]
You can modify the file `MMM-RandomQuranAyah.css` for different style of arabic font on section `.txt-arabic`. Currently, it is using system default arabic font.
